OnlineStore/Models/EF/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineStore.Models.EF
{
    [Table("tb_ProductCategory")]
    public class ProductCategory:CommonAbstract
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }
        public string Description { get; set; }
        [StringLength(250)]
        public string Icon { get; set; }
        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(250)]
        public string SeoKeywords { get; set; }

        public ICollection<Product> Products { get; set; }
    }
}

OnlineStore/Areas/Admin/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Models;
using OnlineStore.Models.EF;

namespace OnlineStore.Areas.admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: admin/ProductCategory
        public ActionResult Index()
        {
            var items = db.ProductCategories;
            return View(items);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Alias = OnlineStore.Models.Common.Filter.FilterChar(model.Title);
                db.ProductCategories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            var item = db.ProductCategories.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedDate = DateTime.Now;
                model.Alias = OnlineStore.Models.Common.Filter.FilterChar(model.Title);
                db.ProductCategories.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

OnlineStore/Areas/Admin/Views/ProductCategory/Add.cshtml
@model OnlineStore.Models.EF.ProductCategory
@{
    ViewBag.Title = "Thêm mới danh mục sản phẩm";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/news" class="nav-link">danh mục sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">danh mục sản phẩm</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin thêm mới Tin tức</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu đề</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alias</label>
                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Ảnh</label>
                        <div class="input-group">
                            <div class="custom-file">
                                @Html.TextBoxFor(x => x.Icon, new { @id = "txtImage", @class = "form-control" })
                            </div>
                            <div class="input-group-append">
                                <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage');" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Seo title</label>
                        @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoDescription</label>
                        @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoKeywords</label>
                        @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                    </div>
                    <div class="form-group">

                        <button type="submit" class="btn btn-primary">Lưu</button>
                        <a href="/admin/news" class="btn btn-danger">Quay lại</a>
                    </div>
                </div>

                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section  scripts{
    <script>
          $(document).ready(function () {
              CKEDITOR.replace('txtDetail', {
                  customConfig: '/content/ckeditor/config.js',
                  extraAllowedContent: 'span',
              });
          });
          function BrowseServer(field) {
              var finder = new CKFinder();
              finder.selectActionFunction = function (fileUrl) {
                  document.getElementById(field).value = fileUrl;
              };
              finder.popup();
          }

    </script>
}

OnlineStore/Areas/Admin/Views/ProductCategory/Edit.cshtml
@model OnlineStore.Models.EF.ProductCategory
@{
    ViewBag.Title = "Cập nhật danh mục sản phẩm";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/news" class="nav-link">danh mục sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập nhật</a>
        </li>
    </ul>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập nhật danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">danh mục sản phẩm</a></li>
                    <li class="breadcrumb-item active">Cập nhật</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin Cập nhật</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "ProductCategory", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x=>x.Id)
                    @Html.HiddenFor(x=>x.CreatedDate)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu đề</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tiêu đề" })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Ảnh</label>
                        <div class="input-group">
                            <div class="custom-file">
                                @Html.TextBoxFor(x => x.Icon, new { @id = "txtImage", @class = "form-control" })
                            </div>
                            <div class="input-group-append">
                                <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage');" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alias</label>
                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Alias" })
                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Seo title</label>
                        @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoDescription</label>
                        @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SeoKeywords</label>
                        @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                    </div>
                    <div class="form-group">

                        <button type="submit" class="btn btn-primary">Lưu</button>
                        <a href="/admin/news" class="btn btn-danger">Quay lại</a>
                    </div>
                </div>

                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section  scripts{
    <script>
          $(document).ready(function () {
              CKEDITOR.replace('txtDetail', {
                  customConfig: '/content/ckeditor/config.js',
                  extraAllowedContent: 'span',
              });
          });
          function BrowseServer(field) {
              var finder = new CKFinder();
              finder.selectActionFunction = function (fileUrl) {
                  document.getElementById(field).value = fileUrl;
              };
              finder.popup();
          }

    </script>
}

OnlineStore/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<OnlineStore.Models.EF.ProductCategory>
@{
    ViewBag.Title = "Danh mục sản phẩm";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}



@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/productcategory" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lý danh mục sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách @ViewBag.Title</h3>

            <div class="card-tools">
                <a href="/admin/ProductCategory/add" class="btn btn-primary">Thêm mới</a>
                <a href="#" class="btn btn-danger" id="BtnDeleteAll">Xóa</a>
            </div>
        </div>
        <div class="card-body">
          
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="SelectAll" /></th>
                        <th>STT</th>
                        <th>Tiêu đề</th>
                        <th>Ngày tạo</th>
                        @*<th>Hiển thị</th>*@

                        <th style="width:150px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i =  1;
                        foreach (var item in Model)
                        {
                            //var strCheck = item.IsActive ? "<i class='fa fa-check text-success'></i>" : "<i class='fas fa-times text-danger'></i>";
                            <tr id="trow_@item.Id">
                                <td><input type="checkbox" class="cbkItem" value="@item.Id" /></td>
                                <td>@i</td>
                                <td>@item.Title</td>
                                <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                @*<td class="text-center">
                                    <a href='#' data-id="@item.Id" class="btnActive">@Html.Raw(strCheck)</a>
                                </td>*@
                                <td>
                                    <a href="/admin/productcategory/edit/@item.Id" class="btn btn-sm btn-primary">Sửa</a>
                                    <a href="#" data-id="@item.Id" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào!!!</td>
                        </tr>
                    }
                </tbody>
            </table>

           

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '#BtnDeleteAll', function (e) {
                e.preventDefault();
                var str = "";
                var checkbox = $(this).parents('.card').find('tr td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa các bản ghi này hay không?');
                    if (conf === true) {
                        $.ajax({
                            url: '/admin/news/deleteAll',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            });

            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
            });
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/news/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });

            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/admin/news/IsActive',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        if (rs.success) {
                            if (rs.isAcive) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                                //$(this).find("i").removeClass("fas fa-times text-danger")
                                //$(this).find("i").addClass("fa fa-check text-success");
                            } else {
                                btn.html("<i class='fas fa-times text-danger'></i>");
                            }
                        }

                    }
                });
            });
        });
    </script>
}